version: "3.8"
services:
  dev: &default
    build:
      context: .
      target: dev
    ports:
      - "8001:8080"
    volumes:
      - ./:/work
  dev:
    <<: *default
    command: tail -f /dev/null