name: pyweb-logging
channels:
  - conda-forge
dependencies:
  - python=3.9
  - flask=2.1.1
  - flask-injector=0.13.0
  - injector=0.19.0
  - PyYAML=6.0
  - flask-swagger=0.2.14
  - dataclasses-json=0.5.7